install:
  root: /mnt
  target_disk: /dev/sda
  user: archuser
  hostname: arch-host
  default_profile: desktop
packages:
  pacman:
    base:
      - base
      - linux
      - linux-firmware
      - sudo
      - networkmanager
      - seatd
      - git
      - base-devel
    desktop:
      - pipewire
      - wireplumber
      - pipewire-alsa
      - pipewire-pulse
      - pipewire-jack
      - xdg-desktop-portal
      - xdg-desktop-portal-wlr
      - xdg-user-dirs
    hyprland:
      - hyprland
      - hyprpaper
      - waybar
      - alacritty
      - grim
      - slurp
      - wl-clipboard
      - wofi
    devtools:
      - man-db
      - man-pages
    fonts:
      - noto-fonts
      - noto-fonts-cjk
      - noto-fonts-emoji
      - ttf-dejavu
    gaming:
      - steam
      - gamemode
      - mangohud
    utils:
      - firefox
      - htop
      - unzip
      - curl
      - wget
  aur:
    default: []
    amd_gpu: []
    intel_gpu: []
    nvidia_gpu:
      - nvidia-vaapi-driver
services:
  - NetworkManager.service
  - systemd-timesyncd.service
  - seatd.service
profiles:
  desktop:
    flags:
      ENABLE_DESKTOP: 1
      ENABLE_HYPRLAND: 1
      ENABLE_DEVTOOLS: 1
      ENABLE_FONTS: 1
      ENABLE_GAMING: 0
      ENABLE_VIRTUALIZATION: 1
    pacman_groups:
      - base
      - desktop
      - hyprland
      - devtools
      - fonts
      - utils
    aur_groups:
      - default
  minimal:
    flags:
      ENABLE_DESKTOP: 0
      ENABLE_HYPRLAND: 0
      ENABLE_DEVTOOLS: 1
      ENABLE_FONTS: 1
      ENABLE_GAMING: 0
      ENABLE_VIRTUALIZATION: 1
    pacman_groups:
      - base
      - devtools
      - fonts
      - utils
    aur_groups:
      - default
